# Generated by Django 5.0.1 on 2024-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=' profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
